version: '3.8'
services:
  user-service:
    build:  ./user-service 
    environment:
      MONGO_URI: mongodb+srv://danduabhiramsai:0G7HDzSo6F5jVjoS@cluster0.sg21eed.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

    ports:
      - "3001:3001"
    networks:
      - backend

  product-service:
    build: ./product-service
    environment:
      MONGO_URI: mongodb+srv://danduabhiramsai:0G7HDzSo6F5jVjoS@cluster0.sg21eed.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

    ports:
      - "3002:3002"
    networks:
      - backend


  order-service:
    build: ./order-service
    environment:
      MONGO_URI: mongodb+srv://danduabhiramsai:0G7HDzSo6F5jVjoS@cluster0.sg21eed.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

    ports:
      - "3003:3003"
    networks:
      - backend

  mongo:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend

  reverse:

    build: ./nginx
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - user-service
      - product-service
      - order-service

networks:
  backend:
    driver: bridge
